### ISSUE TITLE
How to use filament-themes with Laravel and Vite ? 

### ISSUE THREAD

**Issue by Ariziky** [yepsua/filament-themes#1]
I wish to know how to use the package with the new Laravel version using Vite? Thanks.

**Comment by oyepez003** [comment]
Hi, @Ariziky you can keep the `tailwind.config.js` as the documentation says.

Read more about how to configure the Filament themes using Vite and PostCSS in the filament official documentation:

https://filamentphp.com/docs/2.x/admin/appearance#building-themes

If you have any other questions you can reopen the issue.

Thanks!.
